import { useEffect, useState } from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Breadcrumb from "@/components/Breadcrumb";
import useSEO from "@/hooks/useSEO";
import { Search } from "lucide-react";
import { Input } from "@/components/ui/input";

interface GlossaryTerm {
  term: string;
  definition: string;
  category: string;
}

const glossaryTerms: GlossaryTerm[] = [
  {
    term: "AEO (Answer Engine Optimization)",
    definition: "The process of making your business information easy for AI assistants (like ChatGPT, Siri, and Alexa) to find and share. It ensures that when someone asks an AI a question about your business, the AI gives the right answer.",
    category: "A",
  },
  {
    term: "Agentic AI",
    definition: "AI that can act on its own to complete a task. For example, an AI receptionist that doesn't just talk but also books an appointment on your calendar without needing a human to step in.",
    category: "A",
  },
  {
    term: "AI Answering Service",
    definition: "A modern version of a traditional answering service that uses artificial intelligence instead of human operators to handle incoming calls 24/7.",
    category: "A",
  },
  {
    term: "AI Receptionist",
    definition: "A digital assistant that uses voice technology and artificial intelligence to answer phone calls, answer questions, and perform tasks like a human receptionist.",
    category: "A",
  },
  {
    term: "API (Application Programming Interface)",
    definition: "A technical 'bridge' that allows two different software programs to talk to each other—for example, allowing your AI receptionist to send lead data directly into your CRM.",
    category: "A",
  },
  {
    term: "Artificial Intelligence (AI)",
    definition: "Computer systems designed to perform tasks that normally require human intelligence, such as understanding speech, making decisions, and solving problems.",
    category: "A",
  },
  {
    term: "Barge-in",
    definition: "A feature that allows a human caller to interrupt the AI while it is speaking. The AI will stop talking and listen, making the conversation feel more natural and less like a recording.",
    category: "B",
  },
  {
    term: "Bounded Autonomy",
    definition: "A way of setting 'guardrails' for an AI so it can work independently but only within the rules and limits you define for your business.",
    category: "B",
  },
  {
    term: "Business Logic",
    definition: "The specific rules and information that govern how your business operates—such as your hours, pricing, and how you want different types of calls handled.",
    category: "B",
  },
  {
    term: "Call Routing",
    definition: "The process of directing a phone call to the right person or department based on what the caller needs.",
    category: "C",
  },
  {
    term: "Cloud-Based",
    definition: "Software that runs on the internet rather than on a specific computer in your office, allowing it to be accessed from anywhere and scale as your business grows.",
    category: "C",
  },
  {
    term: "Cold Transfer",
    definition: "When a call is transferred directly to another person without the person who is transferring the call speaking to the recipient first.",
    category: "C",
  },
  {
    term: "Conversational AI",
    definition: "A type of AI specifically designed to have back-and-forth conversations with humans using natural language.",
    category: "C",
  },
  {
    term: "CRM (Customer Relationship Management)",
    definition: "Software used by businesses to keep track of all their interactions with customers and potential leads (e.g., HubSpot, Salesforce).",
    category: "C",
  },
  {
    term: "Data Privacy",
    definition: "The practice of protecting sensitive information collected during calls to ensure it is handled securely and in compliance with laws like HIPAA or GDPR.",
    category: "D",
  },
  {
    term: "Digital Teammate",
    definition: "A term used to describe an AI agent that works alongside your human staff to handle repetitive tasks, allowing your team to focus on higher-value work.",
    category: "D",
  },
  {
    term: "GEO (Generative Engine Optimization)",
    definition: "A strategy to ensure your business is accurately represented in the 'answers' generated by AI search engines like Google's AI Overviews or Perplexity.",
    category: "G",
  },
  {
    term: "HIPAA Compliance",
    definition: "A set of US federal standards designed to protect sensitive patient health information from being disclosed without the patient's consent or knowledge.",
    category: "H",
  },
  {
    term: "Human-in-the-Loop (HITL)",
    definition: "A system where humans oversee and check the work of an AI to ensure it is accurate, helpful, and staying on-brand.",
    category: "H",
  },
  {
    term: "Inbound Call",
    definition: "A phone call that is initiated by a customer or prospect and received by your business.",
    category: "I",
  },
  {
    term: "Intent Recognition",
    definition: "The AI's ability to understand what a caller actually wants (e.g., 'I have a leak' means they need an emergency plumber) even if they don't use specific keywords.",
    category: "I",
  },
  {
    term: "Latency",
    definition: "The slight delay between when a person speaks and when the AI responds. Lower latency makes the conversation feel more natural and 'real-time.'",
    category: "L",
  },
  {
    term: "Lead Qualification",
    definition: "The process of asking a caller questions to see if they are a good fit for your services before booking an appointment or passing them to a sales team.",
    category: "L",
  },
  {
    term: "LLM (Large Language Model)",
    definition: "The underlying technology (like GPT-4) that gives an AI its ability to understand and generate human-like text and speech.",
    category: "L",
  },
  {
    term: "Natural Language Processing (NLP)",
    definition: "The field of AI that focuses on helping computers understand, interpret, and respond to human language in a way that is both meaningful and natural.",
    category: "N",
  },
  {
    term: "Outbound Call",
    definition: "A phone call initiated by your business (or your AI agent) to a customer or prospect for follow-up or sales outreach.",
    category: "O",
  },
  {
    term: "Persona",
    definition: "The 'personality' given to an AI, including its tone of voice, level of formality, and conversational style.",
    category: "P",
  },
  {
    term: "Prompt",
    definition: "The specific instructions given to an AI to tell it how to behave and what information to use during a conversation.",
    category: "P",
  },
  {
    term: "Sentiment Analysis",
    definition: "The ability of an AI to detect the emotional tone of a caller—such as whether they are happy, frustrated, or in a hurry.",
    category: "S",
  },
  {
    term: "Speed to Lead",
    definition: "The amount of time it takes for a business to respond to a new inquiry. AI can reduce this to seconds by answering every call immediately.",
    category: "S",
  },
  {
    term: "Transcription",
    definition: "The process of converting the spoken words of a phone call into written text for record-keeping and analysis.",
    category: "T",
  },
  {
    term: "Virtual Receptionist",
    definition: "A broad term that can refer to either a remote human answering service or an AI-powered system that handles front-desk tasks.",
    category: "V",
  },
  {
    term: "Voice Cloning",
    definition: "A technology that creates a digital version of a specific person's voice so the AI can sound exactly like a particular individual.",
    category: "V",
  },
  {
    term: "Voice-to-Text",
    definition: "The technology that translates spoken words into digital text in real-time.",
    category: "V",
  },
  {
    term: "Warm Transfer",
    definition: "When a call is transferred to another person, but the person transferring the call speaks to the recipient first to introduce the caller and provide context.",
    category: "W",
  },
  {
    term: "Webhook",
    definition: "A way for one app to send real-time information to another app as soon as something happens (like an AI booking an appointment and immediately notifying your calendar).",
    category: "W",
  },
];

const Glossary = () => {
  const [searchQuery, setSearchQuery] = useState("");
  const [filteredTerms, setFilteredTerms] = useState(glossaryTerms);

  useSEO({
    title: "AI Receptionist Glossary | BrightLaunchIQ",
    description: "A comprehensive guide to the terms and technology behind the next generation of business communication. Learn about AEO, Agentic AI, NLP, and more.",
    canonical: "https://brightlaunchiq.com/ai-receptionist/resources/glossary",
    keywords: "AI glossary, AI receptionist terms, AEO definition, voice AI technology, business automation glossary",
    speakable: ["h1", ".glossary-intro"],
  });

  useEffect(() => {
    const filtered = glossaryTerms.filter(
      (item) =>
        item.term.toLowerCase().includes(searchQuery.toLowerCase()) ||
        item.definition.toLowerCase().includes(searchQuery.toLowerCase())
    );
    setFilteredTerms(filtered);
  }, [searchQuery]);

  // Add DefinedTermSet schema
  useEffect(() => {
    const existingSchema = document.getElementById("glossary-schema");
    if (existingSchema) existingSchema.remove();

    const schemaScript = document.createElement("script");
    schemaScript.type = "application/ld+json";
    schemaScript.id = "glossary-schema";
    schemaScript.textContent = JSON.stringify({
      "@context": "https://schema.org",
      "@type": "DefinedTermSet",
      "name": "AI Receptionist Glossary",
      "description": "A comprehensive guide to the terms and technology behind the next generation of business communication.",
      "url": "https://brightlaunchiq.com/ai-receptionist/resources/glossary",
      "inLanguage": "en-US",
      "publisher": {
        "@type": "Organization",
        "name": "BrightLaunchIQ",
        "url": "https://brightlaunchiq.com"
      },
      "hasDefinedTerm": glossaryTerms.map((item, index) => ({
        "@type": "DefinedTerm",
        "name": item.term,
        "description": item.definition,
        "url": `https://brightlaunchiq.com/ai-receptionist/resources/glossary#${item.term.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
        "inDefinedTermSet": "https://brightlaunchiq.com/ai-receptionist/resources/glossary",
        "termCode": `BLIQ-GL-${String(index + 1).padStart(3, '0')}`
      })),
    });
    document.head.appendChild(schemaScript);

    return () => {
      const el = document.getElementById("glossary-schema");
      if (el) el.remove();
    };
  }, []);

  const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");

  return (
    <div className="min-h-screen bg-background">
      <Header />

      <main id="main-content" className="pt-24">
        <div className="container">
          <Breadcrumb />
        </div>

        {/* Hero */}
        <section className="py-12 md:py-16 bg-gradient-subtle">
          <div className="container">
            <div className="max-w-4xl mx-auto text-center">
              <h1 className="font-display text-4xl md:text-5xl font-bold text-foreground mb-4">
                AI Receptionist Glossary
              </h1>
              <p className="glossary-intro text-lg text-muted-foreground max-w-2xl mx-auto mb-8">
                A comprehensive guide to the terms and technology behind the next generation of business communication.
              </p>
              <div className="max-w-md mx-auto relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
                <Input
                  type="search"
                  placeholder="Search terms..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-10"
                />
              </div>
            </div>
          </div>
        </section>

        {/* Terms */}
        <section className="py-12 md:py-16">
          <div className="container">
            <div className="max-w-4xl mx-auto">
              {/* Alphabet Quick Links */}
              <div className="flex flex-wrap justify-center gap-2 mb-12">
                {alphabet.map((letter) => {
                  const hasTerms = glossaryTerms.some(t => t.category === letter);
                  return (
                    <a
                      key={letter}
                      href={hasTerms ? `#section-${letter}` : undefined}
                      className={`w-8 h-8 flex items-center justify-center rounded-lg text-sm font-bold transition-all ${
                        hasTerms 
                          ? "bg-primary/10 text-primary hover:bg-primary hover:text-primary-foreground" 
                          : "text-muted-foreground/30 cursor-not-allowed"
                      }`}
                    >
                      {letter}
                    </a>
                  );
                })}
              </div>

              {/* Terms list */}
              <div className="space-y-16">
                {alphabet.map((letter) => {
                  const sectionTerms = filteredTerms.filter(t => t.category === letter);
                  if (sectionTerms.length === 0) return null;

                  return (
                    <div key={letter} id={`section-${letter}`} className="scroll-mt-24">
                      <div className="flex items-center gap-4 mb-8">
                        <h2 className="text-4xl font-bold text-primary/20 font-display">{letter}</h2>
                        <div className="h-px flex-1 bg-border"></div>
                      </div>
                      <div className="grid gap-6">
                        {sectionTerms.map((item) => (
                          <article
                            key={item.term}
                            id={item.term.toLowerCase().replace(/[^a-z0-9]+/g, "-")}
                            className="bg-card rounded-2xl border border-border p-6 md:p-8 hover:shadow-card-hover transition-all"
                          >
                            <h3 className="font-display text-xl font-bold text-foreground mb-3">
                              {item.term}
                            </h3>
                            <p className="text-muted-foreground leading-relaxed">
                              {item.definition}
                            </p>
                          </article>
                        ))}
                      </div>
                    </div>
                  );
                })}
              </div>

              {filteredTerms.length === 0 && (
                <div className="text-center py-12 text-muted-foreground">
                  No terms found matching "{searchQuery}"
                </div>
              )}
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
};

export default Glossary;
