
INSERT INTO public.email_templates (template_key, name, subject, body_html, description) VALUES
-- AEO Audit initial report
('audit_initial', 'AEO Audit Initial Report', 'Your AEO Visibility Report for {{business_name}}', '<h2>Your AEO Visibility Report</h2><p>Hi there,</p><p>Thank you for running your AEO Visibility Audit for <strong>{{business_name}}</strong>.</p><p>Here are your results:</p><ul><li><strong>Current Score:</strong> {{overall_score}}/100</li><li><strong>Potential Score:</strong> {{potential_score}}/100</li><li><strong>Room to Improve:</strong> {{score_improvement}} points</li></ul><p>Your report includes personalized recommendations to improve your visibility in AI-powered search results.</p><p>When you''re ready to take action, schedule a free strategy call:</p><p><a href="https://brightlaunchiq.com/contact">Book a 15-Minute Call</a></p><p>— The BrightLaunchIQ Team</p>', 'Sent immediately after AEO Audit submission with score results.'),

-- AI Receptionist Assessment initial report
('quiz_initial', 'Assessment Initial Report', 'Your Missed Call Results for {{business_name}}', '<p>Hi {{first_name}},</p><p>Here are the results from your Missed Call Revenue Calculator.</p><p>Based on the numbers you entered, <strong>{{business_name}}</strong> may be losing an estimated <strong>{{annual_loss}}</strong> per year from missed calls.</p><p>Here''s what drove that number:</p><ul><li>You miss an average of {{missed_calls}} calls per day</li><li>Your average customer value is {{customer_value}}</li><li>50% of missed callers typically contact a competitor immediately</li></ul><p>When you''re ready to review your options, feel free to call our Live AI Receptionist at <strong>1-877-879-5552</strong>, or you can <a href="https://brightlaunchiq.com/contact">schedule a 15-minute call with a human</a>.</p><p>— The BrightLaunchIQ Team</p>', 'Sent immediately after Assessment submission with missed call revenue estimate.'),

-- AI Receptionist Assessment follow-ups
('quiz_followup_day_2', 'Assessment Day 2 Follow-up', 'It''s more than just {{annual_loss}}, {{first_name}}', '<p>Hi {{first_name}},</p><p>Yesterday, we calculated that {{business_name}} is losing an estimated {{annual_loss}} annually to missed calls. But the true cost is even higher.</p><p>It''s not just about the immediate lost revenue. It''s about the long-term impact:</p><ul><li><strong>Damaged Reputation:</strong> Every missed call is a poor customer experience. 85% of people who can''t reach you won''t call back — they''ll call your competitor.</li><li><strong>Wasted Marketing Spend:</strong> How much do you spend on Google Ads, SEO, or social media to make the phone ring? Every missed call is like setting that marketing budget on fire.</li><li><strong>Stunted Growth:</strong> You can''t grow if you''re leaking customers. Plugging the hole in your phone funnel is the single fastest way to accelerate growth.</li></ul><p>Your primary goal was to {{goal_text}}. An AI Receptionist doesn''t just recover lost revenue; it builds a more professional, reliable, and scalable foundation for your entire business.</p><p><a href="https://brightlaunchiq.com/contact">Book a quick 15-minute call with one of our experts</a></p><p>Best,<br/>The Team at BrightLaunchIQ<br/>1-877-879-5552 | results@brightlaunchiq.com</p>', 'Sent 2 days after Assessment. Emphasizes true cost of missed calls.'),

('quiz_followup_day_4', 'Assessment Day 4 Follow-up', 'How a business like yours solved their missed call problem', '<p>Hi {{first_name}},</p><p>A few months ago, a business owner just like you was in the exact same position. They were missing calls during peak hours and after closing, and losing customers to competitors who were quicker to answer the phone.</p><p>They were leaving an estimated $50,000 on the table every year.</p><p>After implementing the BrightLaunchIQ AI Receptionist, they not only recovered that lost revenue but also:</p><ul><li>Increased appointment bookings by 35% by offering 24/7 scheduling.</li><li>Freed up their staff from the constant interruption of the phone.</li><li>Improved their Google reviews, with customers frequently mentioning the professional and efficient phone service.</li></ul><p>You told us your biggest challenge was missing calls {{timing_text}}. This is exactly what our AI Receptionist is built to solve.</p><p>Imagine what you could do with an extra {{annual_loss}} in your business this year.</p><p><a href="https://brightlaunchiq.com/ai-receptionist/get-started">Start your journey and buy now</a></p><p>Or simply reply to this email with any questions you have.</p><p>Best,<br/>The Team at BrightLaunchIQ<br/>1-877-879-5552 | results@brightlaunchiq.com</p>', 'Sent 4 days after Assessment. Case study / social proof messaging.'),

('quiz_followup_day_7', 'Assessment Day 7 Follow-up', 'A simple choice for {{business_name}}', '<p>Hi {{first_name}},</p><p>Over the past week, we''ve talked about the {{annual_loss}} you''re losing to missed calls and how businesses just like yours are solving the problem.</p><p>Ultimately, it comes down to a simple choice:</p><p><strong>Option A:</strong> Continue with the status quo, knowing that a significant portion of your potential customers are going directly to your competitors every single day.</p><p><strong>Option B:</strong> Implement a proven solution that captures 100% of your leads, enhances your professionalism, and provides an immediate return on investment.</p><p>We understand you might have questions. The most common one we hear is, "Will my customers know it''s an AI?" The answer is that most don''t.</p><p><strong>Hear it for yourself:</strong> Call our live AI Receptionist now at <strong>1-877-879-5552</strong>.</p><p><a href="https://brightlaunchiq.com/ai-receptionist/get-started">Buy Now and Start Recovering Your Lost Revenue</a></p><p>This is your last email from this sequence. We''re here if you need us.</p><p>Best,<br/>The Team at BrightLaunchIQ<br/>1-877-879-5552 | results@brightlaunchiq.com</p>', 'Sent 7 days after Assessment. Final follow-up with clear CTA.');
